[project]
name = "polars-talib"
version = "0.2.0"
description = "Polars extension for Ta-Lib: Support Ta-Lib functions in Polars expressions"
readme = "README.md"
license-files = ["LICENSE", "talib-sys/vendor/TA-Lib-LICENSE"]
authors = [
    {name = "yvictor", email = "yvictor3141@gmail.com"}
]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]
keywords = ["polars-extension", "talib", "technical-analysis", "TA-Lib", "polars", "rust", "polars-expr"]
dependencies = ["polars>=1.20,<2"]


[tool.maturin]
module-name = "polars_talib._polars_talib"
python-packages = ["polars_talib"]
python-source = "python"
features = ["pyo3/extension-module"]

[build-system]
requires = ["maturin>=1.15,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "maturin>=1.15,<2",
    "pytest>=8",
    "numpy>=1.26",
    "pytest-benchmark>=5",
    "ta-lib==0.8.1",
]



[tool.ruff]
line-length = 100
fix = true
src = ["python"]
