# Generated by scripts/generate_indicators.py. Do not edit.
import polars as pl
from .utils import register_plugin
from pathlib import Path
lib = Path(__file__).parent

def ac(high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), fastperiod: int = 5, slowperiod: int = 34, signalperiod: int = 5) -> pl.Expr:
    """Accelerator/Decelerator Oscillator (Momentum Indicators). Outputs: real."""
    return register_plugin(args=[high, low], symbol="ac", is_elementwise=False, lib=lib, kwargs={"fastperiod": fastperiod, "slowperiod": slowperiod, "signalperiod": signalperiod})

def _expr_ac(self, low: pl.Expr = pl.col("low"), fastperiod: int = 5, slowperiod: int = 34, signalperiod: int = 5) -> pl.Expr:
    """Accelerator/Decelerator Oscillator (Momentum Indicators). Outputs: real. The receiver is high."""
    return ac(high=self._expr, low=low, fastperiod=fastperiod, slowperiod=slowperiod, signalperiod=signalperiod)

def accbands(high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), close: pl.Expr = pl.col("close"), timeperiod: int = 20) -> pl.Expr:
    """Acceleration Bands (Overlap Studies). Outputs: upperband, middleband, lowerband."""
    return register_plugin(args=[high, low, close], symbol="accbands", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_accbands(self, high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), timeperiod: int = 20) -> pl.Expr:
    """Acceleration Bands (Overlap Studies). Outputs: upperband, middleband, lowerband. The receiver is close."""
    return accbands(high=high, low=low, close=self._expr, timeperiod=timeperiod)

def adr(high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), timeperiod: int = 14) -> pl.Expr:
    """Average Day Range (Volatility Indicators). Outputs: real."""
    return register_plugin(args=[high, low], symbol="adr", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_adr(self, low: pl.Expr = pl.col("low"), timeperiod: int = 14) -> pl.Expr:
    """Average Day Range (Volatility Indicators). Outputs: real. The receiver is high."""
    return adr(high=self._expr, low=low, timeperiod=timeperiod)

def ao(high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), fastperiod: int = 5, slowperiod: int = 34) -> pl.Expr:
    """Awesome Oscillator (Momentum Indicators). Outputs: real."""
    return register_plugin(args=[high, low], symbol="ao", is_elementwise=False, lib=lib, kwargs={"fastperiod": fastperiod, "slowperiod": slowperiod})

def _expr_ao(self, low: pl.Expr = pl.col("low"), fastperiod: int = 5, slowperiod: int = 34) -> pl.Expr:
    """Awesome Oscillator (Momentum Indicators). Outputs: real. The receiver is high."""
    return ao(high=self._expr, low=low, fastperiod=fastperiod, slowperiod=slowperiod)

def avgdev(real: pl.Expr = pl.col("close"), timeperiod: int = 14) -> pl.Expr:
    """Average Deviation (Price Transform). Outputs: real."""
    return register_plugin(args=[real], symbol="avgdev", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_avgdev(self, timeperiod: int = 14) -> pl.Expr:
    """Average Deviation (Price Transform). Outputs: real. The receiver is real."""
    return avgdev(real=self._expr, timeperiod=timeperiod)

def cmf(high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), close: pl.Expr = pl.col("close"), volume: pl.Expr = pl.col("volume"), timeperiod: int = 20) -> pl.Expr:
    """Chaikin Money Flow (Volume Indicators). Outputs: real."""
    return register_plugin(args=[high, low, close, volume], symbol="cmf", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_cmf(self, high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), volume: pl.Expr = pl.col("volume"), timeperiod: int = 20) -> pl.Expr:
    """Chaikin Money Flow (Volume Indicators). Outputs: real. The receiver is close."""
    return cmf(high=high, low=low, close=self._expr, volume=volume, timeperiod=timeperiod)

def cmou(real: pl.Expr = pl.col("close"), timeperiod: int = 14) -> pl.Expr:
    """Chande Momentum Oscillator (Unsmoothed) (Momentum Indicators). Outputs: real."""
    return register_plugin(args=[real], symbol="cmou", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_cmou(self, timeperiod: int = 14) -> pl.Expr:
    """Chande Momentum Oscillator (Unsmoothed) (Momentum Indicators). Outputs: real. The receiver is real."""
    return cmou(real=self._expr, timeperiod=timeperiod)

def coppock(real: pl.Expr = pl.col("close"), wmaperiod: int = 10, roc1period: int = 11, roc2period: int = 14) -> pl.Expr:
    """Coppock Curve (Momentum Indicators). Outputs: real."""
    return register_plugin(args=[real], symbol="coppock", is_elementwise=False, lib=lib, kwargs={"wmaperiod": wmaperiod, "roc1period": roc1period, "roc2period": roc2period})

def _expr_coppock(self, wmaperiod: int = 10, roc1period: int = 11, roc2period: int = 14) -> pl.Expr:
    """Coppock Curve (Momentum Indicators). Outputs: real. The receiver is real."""
    return coppock(real=self._expr, wmaperiod=wmaperiod, roc1period=roc1period, roc2period=roc2period)

def cumsum(real: pl.Expr = pl.col("close")) -> pl.Expr:
    """Cumulative Sum (Math Operators). Outputs: real."""
    return register_plugin(args=[real], symbol="cumsum", is_elementwise=False, lib=lib, kwargs={})

def _expr_cumsum(self) -> pl.Expr:
    """Cumulative Sum (Math Operators). Outputs: real. The receiver is real."""
    return cumsum(real=self._expr)

def cvi(high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), timeperiod: int = 10, rocperiod: int = 10) -> pl.Expr:
    """Chaikin's Volatility (Volatility Indicators). Outputs: real."""
    return register_plugin(args=[high, low], symbol="cvi", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod, "rocperiod": rocperiod})

def _expr_cvi(self, low: pl.Expr = pl.col("low"), timeperiod: int = 10, rocperiod: int = 10) -> pl.Expr:
    """Chaikin's Volatility (Volatility Indicators). Outputs: real. The receiver is high."""
    return cvi(high=self._expr, low=low, timeperiod=timeperiod, rocperiod=rocperiod)

def donchian(high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), timeperiod: int = 20) -> pl.Expr:
    """Donchian Channels (Overlap Studies). Outputs: upperband, middleband, lowerband."""
    return register_plugin(args=[high, low], symbol="donchian", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_donchian(self, low: pl.Expr = pl.col("low"), timeperiod: int = 20) -> pl.Expr:
    """Donchian Channels (Overlap Studies). Outputs: upperband, middleband, lowerband. The receiver is high."""
    return donchian(high=self._expr, low=low, timeperiod=timeperiod)

def dpo(real: pl.Expr = pl.col("close"), timeperiod: int = 20) -> pl.Expr:
    """Detrended Price Oscillator (Momentum Indicators). Outputs: real."""
    return register_plugin(args=[real], symbol="dpo", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_dpo(self, timeperiod: int = 20) -> pl.Expr:
    """Detrended Price Oscillator (Momentum Indicators). Outputs: real. The receiver is real."""
    return dpo(real=self._expr, timeperiod=timeperiod)

def efi(close: pl.Expr = pl.col("close"), volume: pl.Expr = pl.col("volume"), timeperiod: int = 13) -> pl.Expr:
    """Elder's Force Index (Volume Indicators). Outputs: real."""
    return register_plugin(args=[close, volume], symbol="efi", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_efi(self, volume: pl.Expr = pl.col("volume"), timeperiod: int = 13) -> pl.Expr:
    """Elder's Force Index (Volume Indicators). Outputs: real. The receiver is close."""
    return efi(close=self._expr, volume=volume, timeperiod=timeperiod)

def er(real: pl.Expr = pl.col("close"), timeperiod: int = 10) -> pl.Expr:
    """Kaufman Efficiency Ratio (Momentum Indicators). Outputs: real."""
    return register_plugin(args=[real], symbol="er", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_er(self, timeperiod: int = 10) -> pl.Expr:
    """Kaufman Efficiency Ratio (Momentum Indicators). Outputs: real. The receiver is real."""
    return er(real=self._expr, timeperiod=timeperiod)

def eri(high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), close: pl.Expr = pl.col("close"), timeperiod: int = 13) -> pl.Expr:
    """Elder Ray Index (Bull Power / Bear Power) (Momentum Indicators). Outputs: bullpower, bearpower."""
    return register_plugin(args=[high, low, close], symbol="eri", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_eri(self, high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), timeperiod: int = 13) -> pl.Expr:
    """Elder Ray Index (Bull Power / Bear Power) (Momentum Indicators). Outputs: bullpower, bearpower. The receiver is close."""
    return eri(high=high, low=low, close=self._expr, timeperiod=timeperiod)

def fosc(real: pl.Expr = pl.col("close"), timeperiod: int = 5) -> pl.Expr:
    """Forecast Oscillator (Momentum Indicators). Outputs: real."""
    return register_plugin(args=[real], symbol="fosc", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_fosc(self, timeperiod: int = 5) -> pl.Expr:
    """Forecast Oscillator (Momentum Indicators). Outputs: real. The receiver is real."""
    return fosc(real=self._expr, timeperiod=timeperiod)

def fractal(high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), leftbars: int = 2, rightbars: int = 2) -> pl.Expr:
    """Williams Fractal (Momentum Indicators). Outputs: swinghigh, swinglow."""
    return register_plugin(args=[high, low], symbol="fractal", is_elementwise=False, lib=lib, kwargs={"leftbars": leftbars, "rightbars": rightbars})

def _expr_fractal(self, low: pl.Expr = pl.col("low"), leftbars: int = 2, rightbars: int = 2) -> pl.Expr:
    """Williams Fractal (Momentum Indicators). Outputs: swinghigh, swinglow. The receiver is high."""
    return fractal(high=self._expr, low=low, leftbars=leftbars, rightbars=rightbars)

def ha(open: pl.Expr = pl.col("open"), high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), close: pl.Expr = pl.col("close")) -> pl.Expr:
    """Heikin-Ashi Candles (Price Transform). Outputs: haopen, hahigh, halow, haclose."""
    return register_plugin(args=[open, high, low, close], symbol="ha", is_elementwise=False, lib=lib, kwargs={})

def _expr_ha(self, open: pl.Expr = pl.col("open"), high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low")) -> pl.Expr:
    """Heikin-Ashi Candles (Price Transform). Outputs: haopen, hahigh, halow, haclose. The receiver is close."""
    return ha(open=open, high=high, low=low, close=self._expr)

def hma(real: pl.Expr = pl.col("close"), timeperiod: int = 20) -> pl.Expr:
    """Hull Moving Average (Overlap Studies). Outputs: real."""
    return register_plugin(args=[real], symbol="hma", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_hma(self, timeperiod: int = 20) -> pl.Expr:
    """Hull Moving Average (Overlap Studies). Outputs: real. The receiver is real."""
    return hma(real=self._expr, timeperiod=timeperiod)

def imi(open: pl.Expr = pl.col("open"), close: pl.Expr = pl.col("close"), timeperiod: int = 14) -> pl.Expr:
    """Intraday Momentum Index (Momentum Indicators). Outputs: real."""
    return register_plugin(args=[open, close], symbol="imi", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_imi(self, open: pl.Expr = pl.col("open"), timeperiod: int = 14) -> pl.Expr:
    """Intraday Momentum Index (Momentum Indicators). Outputs: real. The receiver is close."""
    return imi(open=open, close=self._expr, timeperiod=timeperiod)

def kc(high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), close: pl.Expr = pl.col("close"), timeperiod: int = 20, atrperiod: int = 10, nbdev: float = 2.0) -> pl.Expr:
    """Keltner Channels (Overlap Studies). Outputs: upperband, middleband, lowerband."""
    return register_plugin(args=[high, low, close], symbol="kc", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod, "atrperiod": atrperiod, "nbdev": nbdev})

def _expr_kc(self, high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), timeperiod: int = 20, atrperiod: int = 10, nbdev: float = 2.0) -> pl.Expr:
    """Keltner Channels (Overlap Studies). Outputs: upperband, middleband, lowerband. The receiver is close."""
    return kc(high=high, low=low, close=self._expr, timeperiod=timeperiod, atrperiod=atrperiod, nbdev=nbdev)

def kdj(high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), close: pl.Expr = pl.col("close"), fastk_period: int = 9, slowk_period: int = 3, slowk_matype: int = 13, slowd_period: int = 3, slowd_matype: int = 13) -> pl.Expr:
    """KDJ Stochastic (Momentum Indicators). Outputs: k, d, j."""
    return register_plugin(args=[high, low, close], symbol="kdj", is_elementwise=False, lib=lib, kwargs={"fastk_period": fastk_period, "slowk_period": slowk_period, "slowk_matype": slowk_matype, "slowd_period": slowd_period, "slowd_matype": slowd_matype})

def _expr_kdj(self, high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), fastk_period: int = 9, slowk_period: int = 3, slowk_matype: int = 13, slowd_period: int = 3, slowd_matype: int = 13) -> pl.Expr:
    """KDJ Stochastic (Momentum Indicators). Outputs: k, d, j. The receiver is close."""
    return kdj(high=high, low=low, close=self._expr, fastk_period=fastk_period, slowk_period=slowk_period, slowk_matype=slowk_matype, slowd_period=slowd_period, slowd_matype=slowd_matype)

def marketfi(high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), volume: pl.Expr = pl.col("volume")) -> pl.Expr:
    """Market Facilitation Index (Volume Indicators). Outputs: real."""
    return register_plugin(args=[high, low, volume], symbol="marketfi", is_elementwise=False, lib=lib, kwargs={})

def _expr_marketfi(self, low: pl.Expr = pl.col("low"), volume: pl.Expr = pl.col("volume")) -> pl.Expr:
    """Market Facilitation Index (Volume Indicators). Outputs: real. The receiver is high."""
    return marketfi(high=self._expr, low=low, volume=volume)

def massi(high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), fastperiod: int = 9, slowperiod: int = 25) -> pl.Expr:
    """Mass Index (Volatility Indicators). Outputs: real."""
    return register_plugin(args=[high, low], symbol="massi", is_elementwise=False, lib=lib, kwargs={"fastperiod": fastperiod, "slowperiod": slowperiod})

def _expr_massi(self, low: pl.Expr = pl.col("low"), fastperiod: int = 9, slowperiod: int = 25) -> pl.Expr:
    """Mass Index (Volatility Indicators). Outputs: real. The receiver is high."""
    return massi(high=self._expr, low=low, fastperiod=fastperiod, slowperiod=slowperiod)

def nvi(close: pl.Expr = pl.col("close"), volume: pl.Expr = pl.col("volume")) -> pl.Expr:
    """Negative Volume Index (Volume Indicators). Outputs: real."""
    return register_plugin(args=[close, volume], symbol="nvi", is_elementwise=False, lib=lib, kwargs={})

def _expr_nvi(self, volume: pl.Expr = pl.col("volume")) -> pl.Expr:
    """Negative Volume Index (Volume Indicators). Outputs: real. The receiver is close."""
    return nvi(close=self._expr, volume=volume)

def percentile(real: pl.Expr = pl.col("close"), timeperiod: int = 30, percentile: float = 50.0) -> pl.Expr:
    """Percentile (nearest rank) (Statistic Functions). Outputs: real."""
    return register_plugin(args=[real], symbol="percentile", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod, "percentile": percentile})

def _expr_percentile(self, timeperiod: int = 30, percentile: float = 50.0) -> pl.Expr:
    """Percentile (nearest rank) (Statistic Functions). Outputs: real. The receiver is real."""
    return percentile(real=self._expr, timeperiod=timeperiod, percentile=percentile)

def percentrank(real: pl.Expr = pl.col("close"), timeperiod: int = 100) -> pl.Expr:
    """Percent Rank (Statistic Functions). Outputs: real."""
    return register_plugin(args=[real], symbol="percentrank", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_percentrank(self, timeperiod: int = 100) -> pl.Expr:
    """Percent Rank (Statistic Functions). Outputs: real. The receiver is real."""
    return percentrank(real=self._expr, timeperiod=timeperiod)

def pvi(close: pl.Expr = pl.col("close"), volume: pl.Expr = pl.col("volume")) -> pl.Expr:
    """Positive Volume Index (Volume Indicators). Outputs: real."""
    return register_plugin(args=[close, volume], symbol="pvi", is_elementwise=False, lib=lib, kwargs={})

def _expr_pvi(self, volume: pl.Expr = pl.col("volume")) -> pl.Expr:
    """Positive Volume Index (Volume Indicators). Outputs: real. The receiver is close."""
    return pvi(close=self._expr, volume=volume)

def pvo(volume: pl.Expr = pl.col("volume"), fastperiod: int = 12, slowperiod: int = 26, matype: int = 1) -> pl.Expr:
    """Percentage Volume Oscillator (Volume Indicators). Outputs: real."""
    return register_plugin(args=[volume], symbol="pvo", is_elementwise=False, lib=lib, kwargs={"fastperiod": fastperiod, "slowperiod": slowperiod, "matype": matype})

def _expr_pvo(self, fastperiod: int = 12, slowperiod: int = 26, matype: int = 1) -> pl.Expr:
    """Percentage Volume Oscillator (Volume Indicators). Outputs: real. The receiver is volume."""
    return pvo(volume=self._expr, fastperiod=fastperiod, slowperiod=slowperiod, matype=matype)

def pvt(close: pl.Expr = pl.col("close"), volume: pl.Expr = pl.col("volume")) -> pl.Expr:
    """Price Volume Trend (Volume Indicators). Outputs: real."""
    return register_plugin(args=[close, volume], symbol="pvt", is_elementwise=False, lib=lib, kwargs={})

def _expr_pvt(self, volume: pl.Expr = pl.col("volume")) -> pl.Expr:
    """Price Volume Trend (Volume Indicators). Outputs: real. The receiver is close."""
    return pvt(close=self._expr, volume=volume)

def qstick(open: pl.Expr = pl.col("open"), close: pl.Expr = pl.col("close"), timeperiod: int = 10) -> pl.Expr:
    """Qstick (Momentum Indicators). Outputs: real."""
    return register_plugin(args=[open, close], symbol="qstick", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_qstick(self, open: pl.Expr = pl.col("open"), timeperiod: int = 10) -> pl.Expr:
    """Qstick (Momentum Indicators). Outputs: real. The receiver is close."""
    return qstick(open=open, close=self._expr, timeperiod=timeperiod)

def rma(real: pl.Expr = pl.col("close"), timeperiod: int = 30) -> pl.Expr:
    """Wilder's Smoothed Moving Average (Overlap Studies). Outputs: real."""
    return register_plugin(args=[real], symbol="rma", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_rma(self, timeperiod: int = 30) -> pl.Expr:
    """Wilder's Smoothed Moving Average (Overlap Studies). Outputs: real. The receiver is real."""
    return rma(real=self._expr, timeperiod=timeperiod)

def rvi(real: pl.Expr = pl.col("close"), timeperiod: int = 14, stddevperiod: int = 10) -> pl.Expr:
    """Relative Volatility Index (Volatility Indicators). Outputs: real."""
    return register_plugin(args=[real], symbol="rvi", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod, "stddevperiod": stddevperiod})

def _expr_rvi(self, timeperiod: int = 14, stddevperiod: int = 10) -> pl.Expr:
    """Relative Volatility Index (Volatility Indicators). Outputs: real. The receiver is real."""
    return rvi(real=self._expr, timeperiod=timeperiod, stddevperiod=stddevperiod)

def rvol(volume: pl.Expr = pl.col("volume"), timeperiod: int = 20) -> pl.Expr:
    """Relative Volume (Volume Indicators). Outputs: real."""
    return register_plugin(args=[volume], symbol="rvol", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_rvol(self, timeperiod: int = 20) -> pl.Expr:
    """Relative Volume (Volume Indicators). Outputs: real. The receiver is volume."""
    return rvol(volume=self._expr, timeperiod=timeperiod)

def smi(high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), close: pl.Expr = pl.col("close"), timeperiod: int = 13, fastperiod: int = 2, slowperiod: int = 25, signalperiod: int = 9) -> pl.Expr:
    """Stochastic Momentum Index (Momentum Indicators). Outputs: smi, smisignal."""
    return register_plugin(args=[high, low, close], symbol="smi", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod, "fastperiod": fastperiod, "slowperiod": slowperiod, "signalperiod": signalperiod})

def _expr_smi(self, high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), timeperiod: int = 13, fastperiod: int = 2, slowperiod: int = 25, signalperiod: int = 9) -> pl.Expr:
    """Stochastic Momentum Index (Momentum Indicators). Outputs: smi, smisignal. The receiver is close."""
    return smi(high=high, low=low, close=self._expr, timeperiod=timeperiod, fastperiod=fastperiod, slowperiod=slowperiod, signalperiod=signalperiod)

def supertrend(high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), close: pl.Expr = pl.col("close"), timeperiod: int = 10, multiplier: float = 3.0) -> pl.Expr:
    """SuperTrend (Overlap Studies). Outputs: supertrend, trend."""
    return register_plugin(args=[high, low, close], symbol="supertrend", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod, "multiplier": multiplier})

def _expr_supertrend(self, high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), timeperiod: int = 10, multiplier: float = 3.0) -> pl.Expr:
    """SuperTrend (Overlap Studies). Outputs: supertrend, trend. The receiver is close."""
    return supertrend(high=high, low=low, close=self._expr, timeperiod=timeperiod, multiplier=multiplier)

def tsi(real: pl.Expr = pl.col("close"), firstperiod: int = 25, secondperiod: int = 13) -> pl.Expr:
    """True Strength Index (Momentum Indicators). Outputs: real."""
    return register_plugin(args=[real], symbol="tsi", is_elementwise=False, lib=lib, kwargs={"firstperiod": firstperiod, "secondperiod": secondperiod})

def _expr_tsi(self, firstperiod: int = 25, secondperiod: int = 13) -> pl.Expr:
    """True Strength Index (Momentum Indicators). Outputs: real. The receiver is real."""
    return tsi(real=self._expr, firstperiod=firstperiod, secondperiod=secondperiod)

def vhf(real: pl.Expr = pl.col("close"), timeperiod: int = 28) -> pl.Expr:
    """Vertical Horizontal Filter (Momentum Indicators). Outputs: real."""
    return register_plugin(args=[real], symbol="vhf", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_vhf(self, timeperiod: int = 28) -> pl.Expr:
    """Vertical Horizontal Filter (Momentum Indicators). Outputs: real. The receiver is real."""
    return vhf(real=self._expr, timeperiod=timeperiod)

def vortex(high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), close: pl.Expr = pl.col("close"), timeperiod: int = 14) -> pl.Expr:
    """Vortex Indicator (Momentum Indicators). Outputs: plusvi, minusvi."""
    return register_plugin(args=[high, low, close], symbol="vortex", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_vortex(self, high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), timeperiod: int = 14) -> pl.Expr:
    """Vortex Indicator (Momentum Indicators). Outputs: plusvi, minusvi. The receiver is close."""
    return vortex(high=high, low=low, close=self._expr, timeperiod=timeperiod)

def vwap(high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), close: pl.Expr = pl.col("close"), volume: pl.Expr = pl.col("volume")) -> pl.Expr:
    """Volume Weighted Average Price (Volume Indicators). Outputs: real."""
    return register_plugin(args=[high, low, close, volume], symbol="vwap", is_elementwise=False, lib=lib, kwargs={})

def _expr_vwap(self, high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), volume: pl.Expr = pl.col("volume")) -> pl.Expr:
    """Volume Weighted Average Price (Volume Indicators). Outputs: real. The receiver is close."""
    return vwap(high=high, low=low, close=self._expr, volume=volume)

def vwma(real: pl.Expr = pl.col("close"), volume: pl.Expr = pl.col("volume"), timeperiod: int = 30) -> pl.Expr:
    """Volume Weighted Moving Average (Overlap Studies). Outputs: real."""
    return register_plugin(args=[real, volume], symbol="vwma", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_vwma(self, volume: pl.Expr = pl.col("volume"), timeperiod: int = 30) -> pl.Expr:
    """Volume Weighted Moving Average (Overlap Studies). Outputs: real. The receiver is real."""
    return vwma(real=self._expr, volume=volume, timeperiod=timeperiod)

def wad(high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low"), close: pl.Expr = pl.col("close")) -> pl.Expr:
    """Williams' Accumulation/Distribution (Momentum Indicators). Outputs: real."""
    return register_plugin(args=[high, low, close], symbol="wad", is_elementwise=False, lib=lib, kwargs={})

def _expr_wad(self, high: pl.Expr = pl.col("high"), low: pl.Expr = pl.col("low")) -> pl.Expr:
    """Williams' Accumulation/Distribution (Momentum Indicators). Outputs: real. The receiver is close."""
    return wad(high=high, low=low, close=self._expr)

def zlema(real: pl.Expr = pl.col("close"), timeperiod: int = 30) -> pl.Expr:
    """Zero-Lag Exponential Moving Average (Overlap Studies). Outputs: real."""
    return register_plugin(args=[real], symbol="zlema", is_elementwise=False, lib=lib, kwargs={"timeperiod": timeperiod})

def _expr_zlema(self, timeperiod: int = 30) -> pl.Expr:
    """Zero-Lag Exponential Moving Average (Overlap Studies). Outputs: real. The receiver is real."""
    return zlema(real=self._expr, timeperiod=timeperiod)

__all__ = ['ac', 'accbands', 'adr', 'ao', 'avgdev', 'cmf', 'cmou', 'coppock', 'cumsum', 'cvi', 'donchian', 'dpo', 'efi', 'er', 'eri', 'fosc', 'fractal', 'ha', 'hma', 'imi', 'kc', 'kdj', 'marketfi', 'massi', 'nvi', 'percentile', 'percentrank', 'pvi', 'pvo', 'pvt', 'qstick', 'rma', 'rvi', 'rvol', 'smi', 'supertrend', 'tsi', 'vhf', 'vortex', 'vwap', 'vwma', 'wad', 'zlema']
GROUPS = {'Momentum Indicators': ['ac', 'ao', 'cmou', 'coppock', 'dpo', 'er', 'eri', 'fosc', 'fractal', 'imi', 'kdj', 'qstick', 'smi', 'tsi', 'vhf', 'vortex', 'wad'], 'Overlap Studies': ['accbands', 'donchian', 'hma', 'kc', 'rma', 'supertrend', 'vwma', 'zlema'], 'Volatility Indicators': ['adr', 'cvi', 'massi', 'rvi'], 'Price Transform': ['avgdev', 'ha'], 'Volume Indicators': ['cmf', 'efi', 'marketfi', 'nvi', 'pvi', 'pvo', 'pvt', 'rvol', 'vwap'], 'Math Operators': ['cumsum'], 'Statistic Functions': ['percentile', 'percentrank']}
STRUCTS = {'accbands': ['upperband', 'middleband', 'lowerband'], 'donchian': ['upperband', 'middleband', 'lowerband'], 'eri': ['bullpower', 'bearpower'], 'fractal': ['swinghigh', 'swinglow'], 'ha': ['haopen', 'hahigh', 'halow', 'haclose'], 'kc': ['upperband', 'middleband', 'lowerband'], 'kdj': ['k', 'd', 'j'], 'smi': ['smi', 'smisignal'], 'supertrend': ['supertrend', 'trend'], 'vortex': ['plusvi', 'minusvi']}

def install(namespace):
    namespace.ac = _expr_ac
    namespace.accbands = _expr_accbands
    namespace.adr = _expr_adr
    namespace.ao = _expr_ao
    namespace.avgdev = _expr_avgdev
    namespace.cmf = _expr_cmf
    namespace.cmou = _expr_cmou
    namespace.coppock = _expr_coppock
    namespace.cumsum = _expr_cumsum
    namespace.cvi = _expr_cvi
    namespace.donchian = _expr_donchian
    namespace.dpo = _expr_dpo
    namespace.efi = _expr_efi
    namespace.er = _expr_er
    namespace.eri = _expr_eri
    namespace.fosc = _expr_fosc
    namespace.fractal = _expr_fractal
    namespace.ha = _expr_ha
    namespace.hma = _expr_hma
    namespace.imi = _expr_imi
    namespace.kc = _expr_kc
    namespace.kdj = _expr_kdj
    namespace.marketfi = _expr_marketfi
    namespace.massi = _expr_massi
    namespace.nvi = _expr_nvi
    namespace.percentile = _expr_percentile
    namespace.percentrank = _expr_percentrank
    namespace.pvi = _expr_pvi
    namespace.pvo = _expr_pvo
    namespace.pvt = _expr_pvt
    namespace.qstick = _expr_qstick
    namespace.rma = _expr_rma
    namespace.rvi = _expr_rvi
    namespace.rvol = _expr_rvol
    namespace.smi = _expr_smi
    namespace.supertrend = _expr_supertrend
    namespace.tsi = _expr_tsi
    namespace.vhf = _expr_vhf
    namespace.vortex = _expr_vortex
    namespace.vwap = _expr_vwap
    namespace.vwma = _expr_vwma
    namespace.wad = _expr_wad
    namespace.zlema = _expr_zlema
