# Generated by scripts/generate_indicators.py. Do not edit.
INTEGER_PARAMETERS = {
    "ac": [
        "fastperiod",
        "slowperiod",
        "signalperiod"
    ],
    "accbands": [
        "timeperiod"
    ],
    "adosc": [
        "fastperiod",
        "slowperiod"
    ],
    "adr": [
        "timeperiod"
    ],
    "adx": [
        "timeperiod"
    ],
    "adxr": [
        "timeperiod"
    ],
    "ao": [
        "fastperiod",
        "slowperiod"
    ],
    "apo": [
        "fastperiod",
        "slowperiod",
        "matype"
    ],
    "aroon": [
        "timeperiod"
    ],
    "aroonosc": [
        "timeperiod"
    ],
    "atr": [
        "timeperiod"
    ],
    "avgdev": [
        "timeperiod"
    ],
    "bbands": [
        "timeperiod",
        "matype"
    ],
    "beta": [
        "timeperiod"
    ],
    "cci": [
        "timeperiod"
    ],
    "cmf": [
        "timeperiod"
    ],
    "cmo": [
        "timeperiod"
    ],
    "cmou": [
        "timeperiod"
    ],
    "coppock": [
        "wmaperiod",
        "roc1period",
        "roc2period"
    ],
    "correl": [
        "timeperiod"
    ],
    "cvi": [
        "timeperiod",
        "rocperiod"
    ],
    "dema": [
        "timeperiod"
    ],
    "donchian": [
        "timeperiod"
    ],
    "dpo": [
        "timeperiod"
    ],
    "dx": [
        "timeperiod"
    ],
    "efi": [
        "timeperiod"
    ],
    "ema": [
        "timeperiod"
    ],
    "er": [
        "timeperiod"
    ],
    "eri": [
        "timeperiod"
    ],
    "fosc": [
        "timeperiod"
    ],
    "fractal": [
        "leftbars",
        "rightbars"
    ],
    "hma": [
        "timeperiod"
    ],
    "imi": [
        "timeperiod"
    ],
    "kama": [
        "timeperiod"
    ],
    "kc": [
        "timeperiod",
        "atrperiod"
    ],
    "kdj": [
        "fastk_period",
        "slowk_period",
        "slowk_matype",
        "slowd_period",
        "slowd_matype"
    ],
    "linearreg": [
        "timeperiod"
    ],
    "linearreg_angle": [
        "timeperiod"
    ],
    "linearreg_intercept": [
        "timeperiod"
    ],
    "linearreg_slope": [
        "timeperiod"
    ],
    "ma": [
        "timeperiod",
        "matype"
    ],
    "macd": [
        "fastperiod",
        "slowperiod",
        "signalperiod"
    ],
    "macdext": [
        "fastperiod",
        "fastmatype",
        "slowperiod",
        "slowmatype",
        "signalperiod",
        "signalmatype"
    ],
    "macdfix": [
        "signalperiod"
    ],
    "massi": [
        "fastperiod",
        "slowperiod"
    ],
    "mavp": [
        "minperiod",
        "maxperiod",
        "matype"
    ],
    "max": [
        "timeperiod"
    ],
    "maxindex": [
        "timeperiod"
    ],
    "mfi": [
        "timeperiod"
    ],
    "midpoint": [
        "timeperiod"
    ],
    "midprice": [
        "timeperiod"
    ],
    "min": [
        "timeperiod"
    ],
    "minindex": [
        "timeperiod"
    ],
    "minmax": [
        "timeperiod"
    ],
    "minmaxindex": [
        "timeperiod"
    ],
    "minus_di": [
        "timeperiod"
    ],
    "minus_dm": [
        "timeperiod"
    ],
    "mom": [
        "timeperiod"
    ],
    "natr": [
        "timeperiod"
    ],
    "percentile": [
        "timeperiod"
    ],
    "percentrank": [
        "timeperiod"
    ],
    "plus_di": [
        "timeperiod"
    ],
    "plus_dm": [
        "timeperiod"
    ],
    "ppo": [
        "fastperiod",
        "slowperiod",
        "matype"
    ],
    "pvo": [
        "fastperiod",
        "slowperiod",
        "matype"
    ],
    "qstick": [
        "timeperiod"
    ],
    "rma": [
        "timeperiod"
    ],
    "roc": [
        "timeperiod"
    ],
    "rocp": [
        "timeperiod"
    ],
    "rocr": [
        "timeperiod"
    ],
    "rocr100": [
        "timeperiod"
    ],
    "rsi": [
        "timeperiod"
    ],
    "rvi": [
        "timeperiod",
        "stddevperiod"
    ],
    "rvol": [
        "timeperiod"
    ],
    "sma": [
        "timeperiod"
    ],
    "smi": [
        "timeperiod",
        "fastperiod",
        "slowperiod",
        "signalperiod"
    ],
    "stddev": [
        "timeperiod"
    ],
    "stoch": [
        "fastk_period",
        "slowk_period",
        "slowk_matype",
        "slowd_period",
        "slowd_matype"
    ],
    "stochf": [
        "fastk_period",
        "fastd_period",
        "fastd_matype"
    ],
    "stochrsi": [
        "timeperiod",
        "fastk_period",
        "fastd_period",
        "fastd_matype"
    ],
    "sum": [
        "timeperiod"
    ],
    "supertrend": [
        "timeperiod"
    ],
    "t3": [
        "timeperiod"
    ],
    "tema": [
        "timeperiod"
    ],
    "trima": [
        "timeperiod"
    ],
    "trix": [
        "timeperiod"
    ],
    "tsf": [
        "timeperiod"
    ],
    "tsi": [
        "firstperiod",
        "secondperiod"
    ],
    "ultosc": [
        "timeperiod1",
        "timeperiod2",
        "timeperiod3"
    ],
    "var": [
        "timeperiod"
    ],
    "vhf": [
        "timeperiod"
    ],
    "vortex": [
        "timeperiod"
    ],
    "vwma": [
        "timeperiod"
    ],
    "willr": [
        "timeperiod"
    ],
    "wma": [
        "timeperiod"
    ],
    "zlema": [
        "timeperiod"
    ]
}
