"""Generate plugins/polars-talib/skills/polars-talib/reference/functions.md from scripts/api.json.

The table lists, for every TA-Lib function, the namespace receiver (the column
that carries the `.ta` call), the remaining inputs, parameters with defaults and
the output names. CI checks that the committed file is current.
"""

import ast
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUT_DEFAULTS = {"real": "close", "real0": "high", "real1": "low"}


def receiver(name, inputs, legacy):
    # Hand-written wrappers use `open` for OHLC functions; generated ones use
    # close when present and the first input otherwise.
    if name in legacy and "open" in inputs:
        return "open"
    if "close" in inputs:
        return "close"
    return inputs[0]


def generate():
    init = (ROOT / "python/polars_talib/__init__.py").read_text()
    legacy = {n.name for n in ast.parse(init).body if isinstance(n, ast.FunctionDef)}
    api = json.loads((ROOT / "scripts/api.json").read_text())
    lines = [
        "# polars_talib function reference (TA-Lib 0.8.1)",
        "",
        "Generated by `scripts/generate_skill_reference.py` from `scripts/api.json`.",
        "",
        "Every function exists in two forms:",
        "",
        "* namespace method: `pl.col(<receiver>).ta.<name>(<other inputs...>, <params...>)`",
        "* module function: `plta.<name>(<inputs in TA-Lib order...>, <params...>)`; positional",
        "  inputs must be `pl.Expr` and default to the columns `open`, `high`, `low`, `close`,",
        "  `volume` (`real` defaults to `close`, `real0`/`real1` to `high`/`low`).",
        "",
        'Multi-output functions return a `pl.Struct`; use `.struct.field("<output>")` or `.unnest()`.',
        "Outputs named `integer` (and `trend`, `swinghigh`, `swinglow`, candlestick patterns) are Int32,",
        "everything else Float64. The receiver column uses the default column name; other inputs",
        "are listed in positional order, not necessarily Python keyword names.",
        "",
        "`matype` parameters accept `polars_talib.MA_Type` or the integers 0=SMA, 1=EMA, 2=WMA,",
        "3=DEMA, 4=TEMA, 5=TRIMA, 6=KAMA, 7=MAMA, 8=T3, 9=HMA, 10=DISABLED, 11=DEFAULT, 12=ZLEMA, 13=RMA.",
        "",
    ]
    for group in dict.fromkeys(f["group"] for f in api):
        lines += [
            f"## {group}",
            "",
            "| function | description | receiver | other inputs | parameters (defaults) | outputs |",
            "|---|---|---|---|---|---|",
        ]
        for f in api:
            if f["group"] != group:
                continue
            inputs = f["inputs"]
            recv = receiver(f["name"], inputs, legacy)
            receiver_column = INPUT_DEFAULTS.get(recv, recv)
            others = ", ".join(i for i in inputs if i != recv) or "-"
            params = ", ".join(f"{p['name']}={p['default']}" for p in f["params"]) or "-"
            outputs = []
            for o in f["outputs"]:
                name = o["name"]
                if len(f["outputs"]) > 1 and name.startswith("real"):
                    name = name[4:]
                outputs.append(name)
            lines.append(
                f"| `{f['name']}` | {f['description']} | {receiver_column} | {others} | {params} | {', '.join(outputs)} |"
            )
        lines.append("")
    out = ROOT / "plugins/polars-talib/skills/polars-talib/reference/functions.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out.relative_to(ROOT)} ({len(api)} functions)")


if __name__ == "__main__":
    generate()
