"""Generate new typed Rust/Polars/Python wrappers from scripts/api.json.

Run after extract_api.py when updating the pinned upstream release.
"""
import ast
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def generate():
    init = (ROOT/'python/polars_talib/__init__.py').read_text()
    old = {n.name for n in ast.parse(init).body if isinstance(n, ast.FunctionDef)}
    api = json.loads((ROOT/'scripts/api.json').read_text())
    added = [f for f in api if f['name'] not in old]
    rust = ['// Generated by scripts/generate_indicators.py. Do not edit.',
            'use serde::Deserialize;', 'use talib_sys::*;']
    plugin = ['// Generated by scripts/generate_indicators.py. Do not edit.',
              'use polars::prelude::*;', 'use pyo3_polars::derive::polars_expr;',
              'use crate::utils::{broadcast_inputs, cast_series_to_f64, get_series_f64_ptr, ta_code2err};',
              'use talib::generated::*;']
    py = ['# Generated by scripts/generate_indicators.py. Do not edit.',
          'import polars as pl', 'from .utils import register_plugin',
          'from pathlib import Path', 'lib = Path(__file__).parent', '']
    groups = {}
    structs = {}
    for f in added:
        n = f['name']; upper = n.upper(); kw = n.title()+'Kwargs'
        inputs = f['inputs']; params = f['params']; outputs = f['outputs']
        # Match existing band field names.
        for o in outputs:
            if len(outputs)>1 and o['name'].startswith('real'):
                o['name'] = o['name'][4:]
        groups.setdefault(f['group'],[]).append(n)
        if len(outputs)>1: structs[n]=[o['name'] for o in outputs]
        if params:
            rust += ['#[derive(Deserialize)]', f'pub struct {kw} {{']
            rust += [f"    pub {p['name']}: {'f64' if p['type']=='double' else 'i32'}," for p in params]
            rust += ['}']
        types = ['f64' if o['type']=='double' else 'i32' for o in outputs]
        ret = 'Vec<'+types[0]+'>' if len(outputs)==1 else '('+', '.join('Vec<'+t+'>' for t in types)+')'
        sig = [f'{i}: &[f64]' for i in inputs] + ([f'kwargs: &{kw}'] if params else [])
        opts = [f"kwargs.{p['name']}"+(' as TA_MAType' if p['type']=='TA_MAType' else '') for p in params]
        rust += [f'pub fn ta_{n}('+', '.join(sig)+f') -> Result<{ret}, TA_RetCode> {{',
                 f'    let len = {inputs[0]}.len();',
                 '    if len > TA_MAX_INDEX as usize + 1 || '+ ' || '.join(f'{i}.len() != len' for i in inputs)+ ' { return Err(TA_RetCode::TA_BAD_PARAM); }',
                 f'    let lookback = unsafe {{ TA_{upper}_Lookback('+', '.join(opts)+') };',
                 '    if lookback < 0 { return Err(TA_RetCode::TA_BAD_PARAM); }',
                 '    let begin = (0..len).find(|&i| '+ ' && '.join(f'!{i}[i].is_nan()' for i in inputs)+').unwrap_or(len);']
        for j,t in enumerate(types):
            rust += [f'    let mut out{j} = vec![{"f64::NAN" if t=="f64" else "0"}; len];']
        result = 'out0' if len(outputs)==1 else '('+', '.join(f'out{j}' for j in range(len(outputs)))+')'
        rust += [f'    if len - begin <= lookback as usize {{ return Ok({result}); }}',
                 '    let mut out_begin = 0;', '    let mut out_size = 0;',
                 '    let offset = begin + lookback as usize;',
                 f'    let code = unsafe {{ TA_{upper}('+', '.join(['0','(len - begin - 1) as i32']+[f'{i}.as_ptr().add(begin)' for i in inputs]+opts+['&mut out_begin','&mut out_size']+[f'out{j}.as_mut_ptr().add(offset)' for j in range(len(outputs))])+') };',
                 '    if code != TA_RetCode::TA_SUCCESS { return Err(code); }',
                 f'    Ok({result})', '}']
        if len(outputs)>1:
            plugin += [f'fn {n}_output(_: &[Field]) -> PolarsResult<Field> {{',
                       '    Ok(Field::new("", DataType::Struct(vec!['+', '.join(f'Field::new("{o["name"]}", DataType::{"Float64" if o["type"]=="double" else "Int32"})' for o in outputs)+'])))','}',
                       f'#[polars_expr(output_type_func={n}_output)]']
        else: plugin += [f'#[polars_expr(output_type={"Float64" if types[0]=="f64" else "Int32"})]']
        plugin += [f'fn {n}(inputs: &[Series]'+(f', kwargs: {kw}' if params else '')+') -> PolarsResult<Series> {',
                   '    let aligned = broadcast_inputs(inputs)?;',
                   '    let len = aligned.first().map_or(0, |s| s.len());',
                   '    let mut prepared = aligned.iter().map(cast_series_to_f64).collect::<PolarsResult<Vec<_>>>()?;']
        for j,i in enumerate(inputs):
            plugin += [f'    let ({i}_ptr, _{i}_owner) = get_series_f64_ptr(&mut prepared[{j}])?;',
                       f'    let {i} = unsafe {{ std::slice::from_raw_parts({i}_ptr, len) }};']
        plugin += [f'    match ta_{n}('+', '.join(inputs+(['&kwargs'] if params else []))+') {']
        if len(outputs)==1:
            plugin += ['        Ok(out) => Ok(Series::from_vec("", out)),']
        else:
            plugin += ['        Ok(('+', '.join(f'out{j}' for j in range(len(outputs)))+')) => Ok(StructChunked::new("", &['+', '.join(f'Series::from_vec("{o["name"]}", out{j})' for j,o in enumerate(outputs))+'])?.into_series()),']
        plugin += ['        Err(code) => ta_code2err(code),','    }','}']
        primary = 'close' if 'close' in inputs else inputs[0]
        def default(i): return 'pl.col("'+('close' if i.startswith('real') else i)+'")'
        ps = [f"{p['name']}: {'float' if p['type']=='double' else 'int'} = {p['default']!r}" for p in params]
        doc = f"{f['description']} ({f['group']}). Outputs: {', '.join(o['name'] for o in outputs)}."
        py += [f'def {n}('+', '.join([f'{i}: pl.Expr = {default(i)}' for i in inputs]+ps)+') -> pl.Expr:',
               f'    """{doc}"""',
               '    return register_plugin('+f'args=[{", ".join(inputs)}], symbol="{n}", is_elementwise=False, lib=lib, kwargs={{'+', '.join(f'"{p["name"]}": {p["name"]}' for p in params)+'})','',
               f'_call_{n} = {n}', '', f'def _expr_{n}('+', '.join(['self']+[f'{i}: pl.Expr = {default(i)}' for i in inputs if i!=primary]+ps)+') -> pl.Expr:',
               f'    """{doc} The receiver is {primary}."""',
               f'    return _call_{n}('+', '.join(f'{i}='+('self._expr' if i==primary else i) for i in inputs)+ (', ' if params else '')+', '.join(f'{p["name"]}={p["name"]}' for p in params)+')','']
    py += ['__all__ = '+repr([f['name'] for f in added]), 'GROUPS = '+repr(groups), 'STRUCTS = '+repr(structs), '', 'def install(namespace):']
    py += [f'    namespace.{f["name"]} = _expr_{f["name"]}' for f in added]
    for path,lines in [('talib/src/generated.rs',rust),('src/generated.rs',plugin),('python/polars_talib/_generated.py',py)]:
        (ROOT/path).write_text('\n'.join(lines)+'\n')
    catalog = ['# Indicator catalog', '', 'Generated from the pinned TA-Lib 0.8.1 API. All 201 functions are available as', '`polars_talib.<name>` and `pl.col(...).ta.<name>`. Use `inspect.signature`', 'for Python argument order and `get_functions_output_struct()` for Struct fields.', '']
    for group in dict.fromkeys(f['group'] for f in api):
        catalog += ['## '+group, '', '| Function | Description |', '| --- | --- |']
        catalog += [f"| `{f['name']}` | {f['description']} |" for f in api if f['group']==group]
        catalog.append('')
    (ROOT/'docs/indicators.md').write_text('\n'.join(catalog)+'\n')
    import subprocess
    subprocess.run(['rustfmt', str(ROOT/'src/generated.rs'), str(ROOT/'talib/src/generated.rs')], check=True)
    print(f'Generated {len(added)} new indicators')

if __name__ == '__main__': generate()
