// Generated by scripts/generate_indicators.py. Do not edit.
use crate::utils::OutputBuffer;
use serde::Deserialize;
use talib_sys::*;
#[derive(Deserialize)]
pub struct AcKwargs {
    pub fastperiod: i32,
    pub slowperiod: i32,
    pub signalperiod: i32,
}
pub fn ta_ac(high: &[f64], low: &[f64], kwargs: &AcKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = high.len();
    if len > TA_MAX_INDEX as usize + 1 || high.len() != len || low.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback =
        unsafe { TA_AC_Lookback(kwargs.fastperiod, kwargs.slowperiod, kwargs.signalperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !high[i].is_nan() && !low[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_AC(
            0,
            (len - begin - 1) as i32,
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            kwargs.fastperiod,
            kwargs.slowperiod,
            kwargs.signalperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct AccbandsKwargs {
    pub timeperiod: i32,
}
pub fn ta_accbands(
    high: &[f64],
    low: &[f64],
    close: &[f64],
    kwargs: &AccbandsKwargs,
) -> Result<(Vec<f64>, Vec<f64>, Vec<f64>), TA_RetCode> {
    let len = high.len();
    if len > TA_MAX_INDEX as usize + 1
        || high.len() != len
        || low.len() != len
        || close.len() != len
    {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_ACCBANDS_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !high[i].is_nan() && !low[i].is_nan() && !close[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok((
            vec![f64::NAN; len],
            vec![f64::NAN; len],
            vec![f64::NAN; len],
        ));
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out1 = OutputBuffer::<f64>::new(len, offset);
    let mut out2 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_ACCBANDS(
            0,
            (len - begin - 1) as i32,
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            close.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
            out1.as_mut_ptr(),
            out2.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    let out1 = unsafe { out1.finish(out_begin, out_size, lookback)? };
    let out2 = unsafe { out2.finish(out_begin, out_size, lookback)? };
    Ok((out0, out1, out2))
}
#[derive(Deserialize)]
pub struct AdrKwargs {
    pub timeperiod: i32,
}
pub fn ta_adr(high: &[f64], low: &[f64], kwargs: &AdrKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = high.len();
    if len > TA_MAX_INDEX as usize + 1 || high.len() != len || low.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_ADR_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !high[i].is_nan() && !low[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_ADR(
            0,
            (len - begin - 1) as i32,
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct AoKwargs {
    pub fastperiod: i32,
    pub slowperiod: i32,
}
pub fn ta_ao(high: &[f64], low: &[f64], kwargs: &AoKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = high.len();
    if len > TA_MAX_INDEX as usize + 1 || high.len() != len || low.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_AO_Lookback(kwargs.fastperiod, kwargs.slowperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !high[i].is_nan() && !low[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_AO(
            0,
            (len - begin - 1) as i32,
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            kwargs.fastperiod,
            kwargs.slowperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct AvgdevKwargs {
    pub timeperiod: i32,
}
pub fn ta_avgdev(real: &[f64], kwargs: &AvgdevKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = real.len();
    if len > TA_MAX_INDEX as usize + 1 || real.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_AVGDEV_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len).find(|&i| !real[i].is_nan()).unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_AVGDEV(
            0,
            (len - begin - 1) as i32,
            real.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct CmfKwargs {
    pub timeperiod: i32,
}
pub fn ta_cmf(
    high: &[f64],
    low: &[f64],
    close: &[f64],
    volume: &[f64],
    kwargs: &CmfKwargs,
) -> Result<Vec<f64>, TA_RetCode> {
    let len = high.len();
    if len > TA_MAX_INDEX as usize + 1
        || high.len() != len
        || low.len() != len
        || close.len() != len
        || volume.len() != len
    {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_CMF_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| {
            !high[i].is_nan() && !low[i].is_nan() && !close[i].is_nan() && !volume[i].is_nan()
        })
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_CMF(
            0,
            (len - begin - 1) as i32,
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            close.as_ptr().add(begin),
            volume.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct CmouKwargs {
    pub timeperiod: i32,
}
pub fn ta_cmou(real: &[f64], kwargs: &CmouKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = real.len();
    if len > TA_MAX_INDEX as usize + 1 || real.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_CMOU_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len).find(|&i| !real[i].is_nan()).unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_CMOU(
            0,
            (len - begin - 1) as i32,
            real.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct CoppockKwargs {
    pub wmaperiod: i32,
    pub roc1period: i32,
    pub roc2period: i32,
}
pub fn ta_coppock(real: &[f64], kwargs: &CoppockKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = real.len();
    if len > TA_MAX_INDEX as usize + 1 || real.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback =
        unsafe { TA_COPPOCK_Lookback(kwargs.wmaperiod, kwargs.roc1period, kwargs.roc2period) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len).find(|&i| !real[i].is_nan()).unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_COPPOCK(
            0,
            (len - begin - 1) as i32,
            real.as_ptr().add(begin),
            kwargs.wmaperiod,
            kwargs.roc1period,
            kwargs.roc2period,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
pub fn ta_cumsum(real: &[f64]) -> Result<Vec<f64>, TA_RetCode> {
    let len = real.len();
    if len > TA_MAX_INDEX as usize + 1 || real.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_CUMSUM_Lookback() };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len).find(|&i| !real[i].is_nan()).unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_CUMSUM(
            0,
            (len - begin - 1) as i32,
            real.as_ptr().add(begin),
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct CviKwargs {
    pub timeperiod: i32,
    pub rocperiod: i32,
}
pub fn ta_cvi(high: &[f64], low: &[f64], kwargs: &CviKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = high.len();
    if len > TA_MAX_INDEX as usize + 1 || high.len() != len || low.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_CVI_Lookback(kwargs.timeperiod, kwargs.rocperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !high[i].is_nan() && !low[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_CVI(
            0,
            (len - begin - 1) as i32,
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            kwargs.timeperiod,
            kwargs.rocperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct DonchianKwargs {
    pub timeperiod: i32,
}
pub fn ta_donchian(
    high: &[f64],
    low: &[f64],
    kwargs: &DonchianKwargs,
) -> Result<(Vec<f64>, Vec<f64>, Vec<f64>), TA_RetCode> {
    let len = high.len();
    if len > TA_MAX_INDEX as usize + 1 || high.len() != len || low.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_DONCHIAN_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !high[i].is_nan() && !low[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok((
            vec![f64::NAN; len],
            vec![f64::NAN; len],
            vec![f64::NAN; len],
        ));
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out1 = OutputBuffer::<f64>::new(len, offset);
    let mut out2 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_DONCHIAN(
            0,
            (len - begin - 1) as i32,
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
            out1.as_mut_ptr(),
            out2.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    let out1 = unsafe { out1.finish(out_begin, out_size, lookback)? };
    let out2 = unsafe { out2.finish(out_begin, out_size, lookback)? };
    Ok((out0, out1, out2))
}
#[derive(Deserialize)]
pub struct DpoKwargs {
    pub timeperiod: i32,
}
pub fn ta_dpo(real: &[f64], kwargs: &DpoKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = real.len();
    if len > TA_MAX_INDEX as usize + 1 || real.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_DPO_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len).find(|&i| !real[i].is_nan()).unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_DPO(
            0,
            (len - begin - 1) as i32,
            real.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct EfiKwargs {
    pub timeperiod: i32,
}
pub fn ta_efi(close: &[f64], volume: &[f64], kwargs: &EfiKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = close.len();
    if len > TA_MAX_INDEX as usize + 1 || close.len() != len || volume.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_EFI_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !close[i].is_nan() && !volume[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_EFI(
            0,
            (len - begin - 1) as i32,
            close.as_ptr().add(begin),
            volume.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct ErKwargs {
    pub timeperiod: i32,
}
pub fn ta_er(real: &[f64], kwargs: &ErKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = real.len();
    if len > TA_MAX_INDEX as usize + 1 || real.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_ER_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len).find(|&i| !real[i].is_nan()).unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_ER(
            0,
            (len - begin - 1) as i32,
            real.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct EriKwargs {
    pub timeperiod: i32,
}
pub fn ta_eri(
    high: &[f64],
    low: &[f64],
    close: &[f64],
    kwargs: &EriKwargs,
) -> Result<(Vec<f64>, Vec<f64>), TA_RetCode> {
    let len = high.len();
    if len > TA_MAX_INDEX as usize + 1
        || high.len() != len
        || low.len() != len
        || close.len() != len
    {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_ERI_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !high[i].is_nan() && !low[i].is_nan() && !close[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok((vec![f64::NAN; len], vec![f64::NAN; len]));
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out1 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_ERI(
            0,
            (len - begin - 1) as i32,
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            close.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
            out1.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    let out1 = unsafe { out1.finish(out_begin, out_size, lookback)? };
    Ok((out0, out1))
}
#[derive(Deserialize)]
pub struct FoscKwargs {
    pub timeperiod: i32,
}
pub fn ta_fosc(real: &[f64], kwargs: &FoscKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = real.len();
    if len > TA_MAX_INDEX as usize + 1 || real.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_FOSC_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len).find(|&i| !real[i].is_nan()).unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_FOSC(
            0,
            (len - begin - 1) as i32,
            real.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct FractalKwargs {
    pub leftbars: i32,
    pub rightbars: i32,
}
pub fn ta_fractal(
    high: &[f64],
    low: &[f64],
    kwargs: &FractalKwargs,
) -> Result<(Vec<i32>, Vec<i32>), TA_RetCode> {
    let len = high.len();
    if len > TA_MAX_INDEX as usize + 1 || high.len() != len || low.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_FRACTAL_Lookback(kwargs.leftbars, kwargs.rightbars) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !high[i].is_nan() && !low[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok((vec![0; len], vec![0; len]));
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<i32>::new(len, offset);
    let mut out1 = OutputBuffer::<i32>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_FRACTAL(
            0,
            (len - begin - 1) as i32,
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            kwargs.leftbars,
            kwargs.rightbars,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
            out1.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    let out1 = unsafe { out1.finish(out_begin, out_size, lookback)? };
    Ok((out0, out1))
}
pub fn ta_ha(
    open: &[f64],
    high: &[f64],
    low: &[f64],
    close: &[f64],
) -> Result<(Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>), TA_RetCode> {
    let len = open.len();
    if len > TA_MAX_INDEX as usize + 1
        || open.len() != len
        || high.len() != len
        || low.len() != len
        || close.len() != len
    {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_HA_Lookback() };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !open[i].is_nan() && !high[i].is_nan() && !low[i].is_nan() && !close[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok((
            vec![f64::NAN; len],
            vec![f64::NAN; len],
            vec![f64::NAN; len],
            vec![f64::NAN; len],
        ));
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out1 = OutputBuffer::<f64>::new(len, offset);
    let mut out2 = OutputBuffer::<f64>::new(len, offset);
    let mut out3 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_HA(
            0,
            (len - begin - 1) as i32,
            open.as_ptr().add(begin),
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            close.as_ptr().add(begin),
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
            out1.as_mut_ptr(),
            out2.as_mut_ptr(),
            out3.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    let out1 = unsafe { out1.finish(out_begin, out_size, lookback)? };
    let out2 = unsafe { out2.finish(out_begin, out_size, lookback)? };
    let out3 = unsafe { out3.finish(out_begin, out_size, lookback)? };
    Ok((out0, out1, out2, out3))
}
#[derive(Deserialize)]
pub struct HmaKwargs {
    pub timeperiod: i32,
}
pub fn ta_hma(real: &[f64], kwargs: &HmaKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = real.len();
    if len > TA_MAX_INDEX as usize + 1 || real.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_HMA_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len).find(|&i| !real[i].is_nan()).unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_HMA(
            0,
            (len - begin - 1) as i32,
            real.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct ImiKwargs {
    pub timeperiod: i32,
}
pub fn ta_imi(open: &[f64], close: &[f64], kwargs: &ImiKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = open.len();
    if len > TA_MAX_INDEX as usize + 1 || open.len() != len || close.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_IMI_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !open[i].is_nan() && !close[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_IMI(
            0,
            (len - begin - 1) as i32,
            open.as_ptr().add(begin),
            close.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct KcKwargs {
    pub timeperiod: i32,
    pub atrperiod: i32,
    pub nbdev: f64,
}
pub fn ta_kc(
    high: &[f64],
    low: &[f64],
    close: &[f64],
    kwargs: &KcKwargs,
) -> Result<(Vec<f64>, Vec<f64>, Vec<f64>), TA_RetCode> {
    let len = high.len();
    if len > TA_MAX_INDEX as usize + 1
        || high.len() != len
        || low.len() != len
        || close.len() != len
    {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_KC_Lookback(kwargs.timeperiod, kwargs.atrperiod, kwargs.nbdev) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !high[i].is_nan() && !low[i].is_nan() && !close[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok((
            vec![f64::NAN; len],
            vec![f64::NAN; len],
            vec![f64::NAN; len],
        ));
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out1 = OutputBuffer::<f64>::new(len, offset);
    let mut out2 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_KC(
            0,
            (len - begin - 1) as i32,
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            close.as_ptr().add(begin),
            kwargs.timeperiod,
            kwargs.atrperiod,
            kwargs.nbdev,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
            out1.as_mut_ptr(),
            out2.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    let out1 = unsafe { out1.finish(out_begin, out_size, lookback)? };
    let out2 = unsafe { out2.finish(out_begin, out_size, lookback)? };
    Ok((out0, out1, out2))
}
#[derive(Deserialize)]
pub struct KdjKwargs {
    pub fastk_period: i32,
    pub slowk_period: i32,
    pub slowk_matype: i32,
    pub slowd_period: i32,
    pub slowd_matype: i32,
}
pub fn ta_kdj(
    high: &[f64],
    low: &[f64],
    close: &[f64],
    kwargs: &KdjKwargs,
) -> Result<(Vec<f64>, Vec<f64>, Vec<f64>), TA_RetCode> {
    let len = high.len();
    if len > TA_MAX_INDEX as usize + 1
        || high.len() != len
        || low.len() != len
        || close.len() != len
    {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe {
        TA_KDJ_Lookback(
            kwargs.fastk_period,
            kwargs.slowk_period,
            kwargs.slowk_matype as TA_MAType,
            kwargs.slowd_period,
            kwargs.slowd_matype as TA_MAType,
        )
    };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !high[i].is_nan() && !low[i].is_nan() && !close[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok((
            vec![f64::NAN; len],
            vec![f64::NAN; len],
            vec![f64::NAN; len],
        ));
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out1 = OutputBuffer::<f64>::new(len, offset);
    let mut out2 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_KDJ(
            0,
            (len - begin - 1) as i32,
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            close.as_ptr().add(begin),
            kwargs.fastk_period,
            kwargs.slowk_period,
            kwargs.slowk_matype as TA_MAType,
            kwargs.slowd_period,
            kwargs.slowd_matype as TA_MAType,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
            out1.as_mut_ptr(),
            out2.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    let out1 = unsafe { out1.finish(out_begin, out_size, lookback)? };
    let out2 = unsafe { out2.finish(out_begin, out_size, lookback)? };
    Ok((out0, out1, out2))
}
pub fn ta_marketfi(high: &[f64], low: &[f64], volume: &[f64]) -> Result<Vec<f64>, TA_RetCode> {
    let len = high.len();
    if len > TA_MAX_INDEX as usize + 1
        || high.len() != len
        || low.len() != len
        || volume.len() != len
    {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_MARKETFI_Lookback() };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !high[i].is_nan() && !low[i].is_nan() && !volume[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_MARKETFI(
            0,
            (len - begin - 1) as i32,
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            volume.as_ptr().add(begin),
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct MassiKwargs {
    pub fastperiod: i32,
    pub slowperiod: i32,
}
pub fn ta_massi(high: &[f64], low: &[f64], kwargs: &MassiKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = high.len();
    if len > TA_MAX_INDEX as usize + 1 || high.len() != len || low.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_MASSI_Lookback(kwargs.fastperiod, kwargs.slowperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !high[i].is_nan() && !low[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_MASSI(
            0,
            (len - begin - 1) as i32,
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            kwargs.fastperiod,
            kwargs.slowperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
pub fn ta_nvi(close: &[f64], volume: &[f64]) -> Result<Vec<f64>, TA_RetCode> {
    let len = close.len();
    if len > TA_MAX_INDEX as usize + 1 || close.len() != len || volume.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_NVI_Lookback() };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !close[i].is_nan() && !volume[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_NVI(
            0,
            (len - begin - 1) as i32,
            close.as_ptr().add(begin),
            volume.as_ptr().add(begin),
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct PercentileKwargs {
    pub timeperiod: i32,
    pub percentile: f64,
}
pub fn ta_percentile(real: &[f64], kwargs: &PercentileKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = real.len();
    if len > TA_MAX_INDEX as usize + 1 || real.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_PERCENTILE_Lookback(kwargs.timeperiod, kwargs.percentile) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len).find(|&i| !real[i].is_nan()).unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_PERCENTILE(
            0,
            (len - begin - 1) as i32,
            real.as_ptr().add(begin),
            kwargs.timeperiod,
            kwargs.percentile,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct PercentrankKwargs {
    pub timeperiod: i32,
}
pub fn ta_percentrank(real: &[f64], kwargs: &PercentrankKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = real.len();
    if len > TA_MAX_INDEX as usize + 1 || real.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_PERCENTRANK_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len).find(|&i| !real[i].is_nan()).unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_PERCENTRANK(
            0,
            (len - begin - 1) as i32,
            real.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
pub fn ta_pvi(close: &[f64], volume: &[f64]) -> Result<Vec<f64>, TA_RetCode> {
    let len = close.len();
    if len > TA_MAX_INDEX as usize + 1 || close.len() != len || volume.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_PVI_Lookback() };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !close[i].is_nan() && !volume[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_PVI(
            0,
            (len - begin - 1) as i32,
            close.as_ptr().add(begin),
            volume.as_ptr().add(begin),
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct PvoKwargs {
    pub fastperiod: i32,
    pub slowperiod: i32,
    pub matype: i32,
}
pub fn ta_pvo(volume: &[f64], kwargs: &PvoKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = volume.len();
    if len > TA_MAX_INDEX as usize + 1 || volume.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe {
        TA_PVO_Lookback(
            kwargs.fastperiod,
            kwargs.slowperiod,
            kwargs.matype as TA_MAType,
        )
    };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len).find(|&i| !volume[i].is_nan()).unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_PVO(
            0,
            (len - begin - 1) as i32,
            volume.as_ptr().add(begin),
            kwargs.fastperiod,
            kwargs.slowperiod,
            kwargs.matype as TA_MAType,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
pub fn ta_pvt(close: &[f64], volume: &[f64]) -> Result<Vec<f64>, TA_RetCode> {
    let len = close.len();
    if len > TA_MAX_INDEX as usize + 1 || close.len() != len || volume.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_PVT_Lookback() };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !close[i].is_nan() && !volume[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_PVT(
            0,
            (len - begin - 1) as i32,
            close.as_ptr().add(begin),
            volume.as_ptr().add(begin),
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct QstickKwargs {
    pub timeperiod: i32,
}
pub fn ta_qstick(
    open: &[f64],
    close: &[f64],
    kwargs: &QstickKwargs,
) -> Result<Vec<f64>, TA_RetCode> {
    let len = open.len();
    if len > TA_MAX_INDEX as usize + 1 || open.len() != len || close.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_QSTICK_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !open[i].is_nan() && !close[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_QSTICK(
            0,
            (len - begin - 1) as i32,
            open.as_ptr().add(begin),
            close.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct RmaKwargs {
    pub timeperiod: i32,
}
pub fn ta_rma(real: &[f64], kwargs: &RmaKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = real.len();
    if len > TA_MAX_INDEX as usize + 1 || real.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_RMA_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len).find(|&i| !real[i].is_nan()).unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_RMA(
            0,
            (len - begin - 1) as i32,
            real.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct RviKwargs {
    pub timeperiod: i32,
    pub stddevperiod: i32,
}
pub fn ta_rvi(real: &[f64], kwargs: &RviKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = real.len();
    if len > TA_MAX_INDEX as usize + 1 || real.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_RVI_Lookback(kwargs.timeperiod, kwargs.stddevperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len).find(|&i| !real[i].is_nan()).unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_RVI(
            0,
            (len - begin - 1) as i32,
            real.as_ptr().add(begin),
            kwargs.timeperiod,
            kwargs.stddevperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct RvolKwargs {
    pub timeperiod: i32,
}
pub fn ta_rvol(volume: &[f64], kwargs: &RvolKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = volume.len();
    if len > TA_MAX_INDEX as usize + 1 || volume.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_RVOL_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len).find(|&i| !volume[i].is_nan()).unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_RVOL(
            0,
            (len - begin - 1) as i32,
            volume.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct SmiKwargs {
    pub timeperiod: i32,
    pub fastperiod: i32,
    pub slowperiod: i32,
    pub signalperiod: i32,
}
pub fn ta_smi(
    high: &[f64],
    low: &[f64],
    close: &[f64],
    kwargs: &SmiKwargs,
) -> Result<(Vec<f64>, Vec<f64>), TA_RetCode> {
    let len = high.len();
    if len > TA_MAX_INDEX as usize + 1
        || high.len() != len
        || low.len() != len
        || close.len() != len
    {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe {
        TA_SMI_Lookback(
            kwargs.timeperiod,
            kwargs.fastperiod,
            kwargs.slowperiod,
            kwargs.signalperiod,
        )
    };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !high[i].is_nan() && !low[i].is_nan() && !close[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok((vec![f64::NAN; len], vec![f64::NAN; len]));
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out1 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_SMI(
            0,
            (len - begin - 1) as i32,
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            close.as_ptr().add(begin),
            kwargs.timeperiod,
            kwargs.fastperiod,
            kwargs.slowperiod,
            kwargs.signalperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
            out1.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    let out1 = unsafe { out1.finish(out_begin, out_size, lookback)? };
    Ok((out0, out1))
}
#[derive(Deserialize)]
pub struct SupertrendKwargs {
    pub timeperiod: i32,
    pub multiplier: f64,
}
pub fn ta_supertrend(
    high: &[f64],
    low: &[f64],
    close: &[f64],
    kwargs: &SupertrendKwargs,
) -> Result<(Vec<f64>, Vec<i32>), TA_RetCode> {
    let len = high.len();
    if len > TA_MAX_INDEX as usize + 1
        || high.len() != len
        || low.len() != len
        || close.len() != len
    {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_SUPERTREND_Lookback(kwargs.timeperiod, kwargs.multiplier) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !high[i].is_nan() && !low[i].is_nan() && !close[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok((vec![f64::NAN; len], vec![0; len]));
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out1 = OutputBuffer::<i32>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_SUPERTREND(
            0,
            (len - begin - 1) as i32,
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            close.as_ptr().add(begin),
            kwargs.timeperiod,
            kwargs.multiplier,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
            out1.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    let out1 = unsafe { out1.finish(out_begin, out_size, lookback)? };
    Ok((out0, out1))
}
#[derive(Deserialize)]
pub struct TsiKwargs {
    pub firstperiod: i32,
    pub secondperiod: i32,
}
pub fn ta_tsi(real: &[f64], kwargs: &TsiKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = real.len();
    if len > TA_MAX_INDEX as usize + 1 || real.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_TSI_Lookback(kwargs.firstperiod, kwargs.secondperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len).find(|&i| !real[i].is_nan()).unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_TSI(
            0,
            (len - begin - 1) as i32,
            real.as_ptr().add(begin),
            kwargs.firstperiod,
            kwargs.secondperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct VhfKwargs {
    pub timeperiod: i32,
}
pub fn ta_vhf(real: &[f64], kwargs: &VhfKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = real.len();
    if len > TA_MAX_INDEX as usize + 1 || real.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_VHF_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len).find(|&i| !real[i].is_nan()).unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_VHF(
            0,
            (len - begin - 1) as i32,
            real.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct VortexKwargs {
    pub timeperiod: i32,
}
pub fn ta_vortex(
    high: &[f64],
    low: &[f64],
    close: &[f64],
    kwargs: &VortexKwargs,
) -> Result<(Vec<f64>, Vec<f64>), TA_RetCode> {
    let len = high.len();
    if len > TA_MAX_INDEX as usize + 1
        || high.len() != len
        || low.len() != len
        || close.len() != len
    {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_VORTEX_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !high[i].is_nan() && !low[i].is_nan() && !close[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok((vec![f64::NAN; len], vec![f64::NAN; len]));
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out1 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_VORTEX(
            0,
            (len - begin - 1) as i32,
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            close.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
            out1.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    let out1 = unsafe { out1.finish(out_begin, out_size, lookback)? };
    Ok((out0, out1))
}
pub fn ta_vwap(
    high: &[f64],
    low: &[f64],
    close: &[f64],
    volume: &[f64],
) -> Result<Vec<f64>, TA_RetCode> {
    let len = high.len();
    if len > TA_MAX_INDEX as usize + 1
        || high.len() != len
        || low.len() != len
        || close.len() != len
        || volume.len() != len
    {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_VWAP_Lookback() };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| {
            !high[i].is_nan() && !low[i].is_nan() && !close[i].is_nan() && !volume[i].is_nan()
        })
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_VWAP(
            0,
            (len - begin - 1) as i32,
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            close.as_ptr().add(begin),
            volume.as_ptr().add(begin),
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct VwmaKwargs {
    pub timeperiod: i32,
}
pub fn ta_vwma(real: &[f64], volume: &[f64], kwargs: &VwmaKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = real.len();
    if len > TA_MAX_INDEX as usize + 1 || real.len() != len || volume.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_VWMA_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !real[i].is_nan() && !volume[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_VWMA(
            0,
            (len - begin - 1) as i32,
            real.as_ptr().add(begin),
            volume.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
pub fn ta_wad(high: &[f64], low: &[f64], close: &[f64]) -> Result<Vec<f64>, TA_RetCode> {
    let len = high.len();
    if len > TA_MAX_INDEX as usize + 1
        || high.len() != len
        || low.len() != len
        || close.len() != len
    {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_WAD_Lookback() };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len)
        .find(|&i| !high[i].is_nan() && !low[i].is_nan() && !close[i].is_nan())
        .unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_WAD(
            0,
            (len - begin - 1) as i32,
            high.as_ptr().add(begin),
            low.as_ptr().add(begin),
            close.as_ptr().add(begin),
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
#[derive(Deserialize)]
pub struct ZlemaKwargs {
    pub timeperiod: i32,
}
pub fn ta_zlema(real: &[f64], kwargs: &ZlemaKwargs) -> Result<Vec<f64>, TA_RetCode> {
    let len = real.len();
    if len > TA_MAX_INDEX as usize + 1 || real.len() != len {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let lookback = unsafe { TA_ZLEMA_Lookback(kwargs.timeperiod) };
    if lookback < 0 {
        return Err(TA_RetCode::TA_BAD_PARAM);
    }
    let begin = (0..len).find(|&i| !real[i].is_nan()).unwrap_or(len);
    if len - begin <= lookback as usize {
        return Ok(vec![f64::NAN; len]);
    }
    let offset = begin + lookback as usize;
    let mut out0 = OutputBuffer::<f64>::new(len, offset);
    let mut out_begin = 0;
    let mut out_size = 0;
    let code = unsafe {
        TA_ZLEMA(
            0,
            (len - begin - 1) as i32,
            real.as_ptr().add(begin),
            kwargs.timeperiod,
            &mut out_begin,
            &mut out_size,
            out0.as_mut_ptr(),
        )
    };
    if code != TA_RetCode::TA_SUCCESS {
        return Err(code);
    }
    // TA_SUCCESS guarantees initialization of the reported output range.
    let out0 = unsafe { out0.finish(out_begin, out_size, lookback)? };
    Ok(out0)
}
