// Generated by scripts/generate_indicators.py. Do not edit.
use crate::utils::{cast_series_to_f64, get_series_f64_ptr, ta_code2err};
use polars::prelude::*;
use pyo3_polars::derive::polars_expr;
use talib::generated::*;
#[polars_expr(output_type=Float64)]
fn ac(inputs: &[Series], kwargs: AcKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    match ta_ac(high, low, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
fn accbands_output(_: &[Field]) -> PolarsResult<Field> {
    Ok(Field::new(
        "",
        DataType::Struct(vec![
            Field::new("upperband", DataType::Float64),
            Field::new("middleband", DataType::Float64),
            Field::new("lowerband", DataType::Float64),
        ]),
    ))
}
#[polars_expr(output_type_func=accbands_output)]
fn accbands(inputs: &[Series], kwargs: AccbandsKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    let (close_ptr, _close_owner) = get_series_f64_ptr(&mut prepared[2])?;
    let close = unsafe { std::slice::from_raw_parts(close_ptr, len) };
    match ta_accbands(high, low, close, &kwargs) {
        Ok((out0, out1, out2)) => Ok(StructChunked::new(
            "",
            &[
                Series::from_vec("upperband", out0),
                Series::from_vec("middleband", out1),
                Series::from_vec("lowerband", out2),
            ],
        )?
        .into_series()),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn adr(inputs: &[Series], kwargs: AdrKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    match ta_adr(high, low, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn ao(inputs: &[Series], kwargs: AoKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    match ta_ao(high, low, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn avgdev(inputs: &[Series], kwargs: AvgdevKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (real_ptr, _real_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let real = unsafe { std::slice::from_raw_parts(real_ptr, len) };
    match ta_avgdev(real, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn cmf(inputs: &[Series], kwargs: CmfKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    let (close_ptr, _close_owner) = get_series_f64_ptr(&mut prepared[2])?;
    let close = unsafe { std::slice::from_raw_parts(close_ptr, len) };
    let (volume_ptr, _volume_owner) = get_series_f64_ptr(&mut prepared[3])?;
    let volume = unsafe { std::slice::from_raw_parts(volume_ptr, len) };
    match ta_cmf(high, low, close, volume, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn cmou(inputs: &[Series], kwargs: CmouKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (real_ptr, _real_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let real = unsafe { std::slice::from_raw_parts(real_ptr, len) };
    match ta_cmou(real, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn coppock(inputs: &[Series], kwargs: CoppockKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (real_ptr, _real_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let real = unsafe { std::slice::from_raw_parts(real_ptr, len) };
    match ta_coppock(real, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn cumsum(inputs: &[Series]) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (real_ptr, _real_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let real = unsafe { std::slice::from_raw_parts(real_ptr, len) };
    match ta_cumsum(real) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn cvi(inputs: &[Series], kwargs: CviKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    match ta_cvi(high, low, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
fn donchian_output(_: &[Field]) -> PolarsResult<Field> {
    Ok(Field::new(
        "",
        DataType::Struct(vec![
            Field::new("upperband", DataType::Float64),
            Field::new("middleband", DataType::Float64),
            Field::new("lowerband", DataType::Float64),
        ]),
    ))
}
#[polars_expr(output_type_func=donchian_output)]
fn donchian(inputs: &[Series], kwargs: DonchianKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    match ta_donchian(high, low, &kwargs) {
        Ok((out0, out1, out2)) => Ok(StructChunked::new(
            "",
            &[
                Series::from_vec("upperband", out0),
                Series::from_vec("middleband", out1),
                Series::from_vec("lowerband", out2),
            ],
        )?
        .into_series()),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn dpo(inputs: &[Series], kwargs: DpoKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (real_ptr, _real_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let real = unsafe { std::slice::from_raw_parts(real_ptr, len) };
    match ta_dpo(real, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn efi(inputs: &[Series], kwargs: EfiKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (close_ptr, _close_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let close = unsafe { std::slice::from_raw_parts(close_ptr, len) };
    let (volume_ptr, _volume_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let volume = unsafe { std::slice::from_raw_parts(volume_ptr, len) };
    match ta_efi(close, volume, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn er(inputs: &[Series], kwargs: ErKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (real_ptr, _real_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let real = unsafe { std::slice::from_raw_parts(real_ptr, len) };
    match ta_er(real, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
fn eri_output(_: &[Field]) -> PolarsResult<Field> {
    Ok(Field::new(
        "",
        DataType::Struct(vec![
            Field::new("bullpower", DataType::Float64),
            Field::new("bearpower", DataType::Float64),
        ]),
    ))
}
#[polars_expr(output_type_func=eri_output)]
fn eri(inputs: &[Series], kwargs: EriKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    let (close_ptr, _close_owner) = get_series_f64_ptr(&mut prepared[2])?;
    let close = unsafe { std::slice::from_raw_parts(close_ptr, len) };
    match ta_eri(high, low, close, &kwargs) {
        Ok((out0, out1)) => Ok(StructChunked::new(
            "",
            &[
                Series::from_vec("bullpower", out0),
                Series::from_vec("bearpower", out1),
            ],
        )?
        .into_series()),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn fosc(inputs: &[Series], kwargs: FoscKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (real_ptr, _real_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let real = unsafe { std::slice::from_raw_parts(real_ptr, len) };
    match ta_fosc(real, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
fn fractal_output(_: &[Field]) -> PolarsResult<Field> {
    Ok(Field::new(
        "",
        DataType::Struct(vec![
            Field::new("swinghigh", DataType::Int32),
            Field::new("swinglow", DataType::Int32),
        ]),
    ))
}
#[polars_expr(output_type_func=fractal_output)]
fn fractal(inputs: &[Series], kwargs: FractalKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    match ta_fractal(high, low, &kwargs) {
        Ok((out0, out1)) => Ok(StructChunked::new(
            "",
            &[
                Series::from_vec("swinghigh", out0),
                Series::from_vec("swinglow", out1),
            ],
        )?
        .into_series()),
        Err(code) => ta_code2err(code),
    }
}
fn ha_output(_: &[Field]) -> PolarsResult<Field> {
    Ok(Field::new(
        "",
        DataType::Struct(vec![
            Field::new("haopen", DataType::Float64),
            Field::new("hahigh", DataType::Float64),
            Field::new("halow", DataType::Float64),
            Field::new("haclose", DataType::Float64),
        ]),
    ))
}
#[polars_expr(output_type_func=ha_output)]
fn ha(inputs: &[Series]) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (open_ptr, _open_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let open = unsafe { std::slice::from_raw_parts(open_ptr, len) };
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[2])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    let (close_ptr, _close_owner) = get_series_f64_ptr(&mut prepared[3])?;
    let close = unsafe { std::slice::from_raw_parts(close_ptr, len) };
    match ta_ha(open, high, low, close) {
        Ok((out0, out1, out2, out3)) => Ok(StructChunked::new(
            "",
            &[
                Series::from_vec("haopen", out0),
                Series::from_vec("hahigh", out1),
                Series::from_vec("halow", out2),
                Series::from_vec("haclose", out3),
            ],
        )?
        .into_series()),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn hma(inputs: &[Series], kwargs: HmaKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (real_ptr, _real_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let real = unsafe { std::slice::from_raw_parts(real_ptr, len) };
    match ta_hma(real, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn imi(inputs: &[Series], kwargs: ImiKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (open_ptr, _open_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let open = unsafe { std::slice::from_raw_parts(open_ptr, len) };
    let (close_ptr, _close_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let close = unsafe { std::slice::from_raw_parts(close_ptr, len) };
    match ta_imi(open, close, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
fn kc_output(_: &[Field]) -> PolarsResult<Field> {
    Ok(Field::new(
        "",
        DataType::Struct(vec![
            Field::new("upperband", DataType::Float64),
            Field::new("middleband", DataType::Float64),
            Field::new("lowerband", DataType::Float64),
        ]),
    ))
}
#[polars_expr(output_type_func=kc_output)]
fn kc(inputs: &[Series], kwargs: KcKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    let (close_ptr, _close_owner) = get_series_f64_ptr(&mut prepared[2])?;
    let close = unsafe { std::slice::from_raw_parts(close_ptr, len) };
    match ta_kc(high, low, close, &kwargs) {
        Ok((out0, out1, out2)) => Ok(StructChunked::new(
            "",
            &[
                Series::from_vec("upperband", out0),
                Series::from_vec("middleband", out1),
                Series::from_vec("lowerband", out2),
            ],
        )?
        .into_series()),
        Err(code) => ta_code2err(code),
    }
}
fn kdj_output(_: &[Field]) -> PolarsResult<Field> {
    Ok(Field::new(
        "",
        DataType::Struct(vec![
            Field::new("k", DataType::Float64),
            Field::new("d", DataType::Float64),
            Field::new("j", DataType::Float64),
        ]),
    ))
}
#[polars_expr(output_type_func=kdj_output)]
fn kdj(inputs: &[Series], kwargs: KdjKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    let (close_ptr, _close_owner) = get_series_f64_ptr(&mut prepared[2])?;
    let close = unsafe { std::slice::from_raw_parts(close_ptr, len) };
    match ta_kdj(high, low, close, &kwargs) {
        Ok((out0, out1, out2)) => Ok(StructChunked::new(
            "",
            &[
                Series::from_vec("k", out0),
                Series::from_vec("d", out1),
                Series::from_vec("j", out2),
            ],
        )?
        .into_series()),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn marketfi(inputs: &[Series]) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    let (volume_ptr, _volume_owner) = get_series_f64_ptr(&mut prepared[2])?;
    let volume = unsafe { std::slice::from_raw_parts(volume_ptr, len) };
    match ta_marketfi(high, low, volume) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn massi(inputs: &[Series], kwargs: MassiKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    match ta_massi(high, low, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn nvi(inputs: &[Series]) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (close_ptr, _close_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let close = unsafe { std::slice::from_raw_parts(close_ptr, len) };
    let (volume_ptr, _volume_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let volume = unsafe { std::slice::from_raw_parts(volume_ptr, len) };
    match ta_nvi(close, volume) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn percentile(inputs: &[Series], kwargs: PercentileKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (real_ptr, _real_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let real = unsafe { std::slice::from_raw_parts(real_ptr, len) };
    match ta_percentile(real, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn percentrank(inputs: &[Series], kwargs: PercentrankKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (real_ptr, _real_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let real = unsafe { std::slice::from_raw_parts(real_ptr, len) };
    match ta_percentrank(real, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn pvi(inputs: &[Series]) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (close_ptr, _close_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let close = unsafe { std::slice::from_raw_parts(close_ptr, len) };
    let (volume_ptr, _volume_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let volume = unsafe { std::slice::from_raw_parts(volume_ptr, len) };
    match ta_pvi(close, volume) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn pvo(inputs: &[Series], kwargs: PvoKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (volume_ptr, _volume_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let volume = unsafe { std::slice::from_raw_parts(volume_ptr, len) };
    match ta_pvo(volume, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn pvt(inputs: &[Series]) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (close_ptr, _close_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let close = unsafe { std::slice::from_raw_parts(close_ptr, len) };
    let (volume_ptr, _volume_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let volume = unsafe { std::slice::from_raw_parts(volume_ptr, len) };
    match ta_pvt(close, volume) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn qstick(inputs: &[Series], kwargs: QstickKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (open_ptr, _open_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let open = unsafe { std::slice::from_raw_parts(open_ptr, len) };
    let (close_ptr, _close_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let close = unsafe { std::slice::from_raw_parts(close_ptr, len) };
    match ta_qstick(open, close, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn rma(inputs: &[Series], kwargs: RmaKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (real_ptr, _real_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let real = unsafe { std::slice::from_raw_parts(real_ptr, len) };
    match ta_rma(real, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn rvi(inputs: &[Series], kwargs: RviKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (real_ptr, _real_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let real = unsafe { std::slice::from_raw_parts(real_ptr, len) };
    match ta_rvi(real, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn rvol(inputs: &[Series], kwargs: RvolKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (volume_ptr, _volume_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let volume = unsafe { std::slice::from_raw_parts(volume_ptr, len) };
    match ta_rvol(volume, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
fn smi_output(_: &[Field]) -> PolarsResult<Field> {
    Ok(Field::new(
        "",
        DataType::Struct(vec![
            Field::new("smi", DataType::Float64),
            Field::new("smisignal", DataType::Float64),
        ]),
    ))
}
#[polars_expr(output_type_func=smi_output)]
fn smi(inputs: &[Series], kwargs: SmiKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    let (close_ptr, _close_owner) = get_series_f64_ptr(&mut prepared[2])?;
    let close = unsafe { std::slice::from_raw_parts(close_ptr, len) };
    match ta_smi(high, low, close, &kwargs) {
        Ok((out0, out1)) => Ok(StructChunked::new(
            "",
            &[
                Series::from_vec("smi", out0),
                Series::from_vec("smisignal", out1),
            ],
        )?
        .into_series()),
        Err(code) => ta_code2err(code),
    }
}
fn supertrend_output(_: &[Field]) -> PolarsResult<Field> {
    Ok(Field::new(
        "",
        DataType::Struct(vec![
            Field::new("supertrend", DataType::Float64),
            Field::new("trend", DataType::Int32),
        ]),
    ))
}
#[polars_expr(output_type_func=supertrend_output)]
fn supertrend(inputs: &[Series], kwargs: SupertrendKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    let (close_ptr, _close_owner) = get_series_f64_ptr(&mut prepared[2])?;
    let close = unsafe { std::slice::from_raw_parts(close_ptr, len) };
    match ta_supertrend(high, low, close, &kwargs) {
        Ok((out0, out1)) => Ok(StructChunked::new(
            "",
            &[
                Series::from_vec("supertrend", out0),
                Series::from_vec("trend", out1),
            ],
        )?
        .into_series()),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn tsi(inputs: &[Series], kwargs: TsiKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (real_ptr, _real_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let real = unsafe { std::slice::from_raw_parts(real_ptr, len) };
    match ta_tsi(real, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn vhf(inputs: &[Series], kwargs: VhfKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (real_ptr, _real_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let real = unsafe { std::slice::from_raw_parts(real_ptr, len) };
    match ta_vhf(real, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
fn vortex_output(_: &[Field]) -> PolarsResult<Field> {
    Ok(Field::new(
        "",
        DataType::Struct(vec![
            Field::new("plusvi", DataType::Float64),
            Field::new("minusvi", DataType::Float64),
        ]),
    ))
}
#[polars_expr(output_type_func=vortex_output)]
fn vortex(inputs: &[Series], kwargs: VortexKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    let (close_ptr, _close_owner) = get_series_f64_ptr(&mut prepared[2])?;
    let close = unsafe { std::slice::from_raw_parts(close_ptr, len) };
    match ta_vortex(high, low, close, &kwargs) {
        Ok((out0, out1)) => Ok(StructChunked::new(
            "",
            &[
                Series::from_vec("plusvi", out0),
                Series::from_vec("minusvi", out1),
            ],
        )?
        .into_series()),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn vwap(inputs: &[Series]) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    let (close_ptr, _close_owner) = get_series_f64_ptr(&mut prepared[2])?;
    let close = unsafe { std::slice::from_raw_parts(close_ptr, len) };
    let (volume_ptr, _volume_owner) = get_series_f64_ptr(&mut prepared[3])?;
    let volume = unsafe { std::slice::from_raw_parts(volume_ptr, len) };
    match ta_vwap(high, low, close, volume) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn vwma(inputs: &[Series], kwargs: VwmaKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (real_ptr, _real_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let real = unsafe { std::slice::from_raw_parts(real_ptr, len) };
    let (volume_ptr, _volume_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let volume = unsafe { std::slice::from_raw_parts(volume_ptr, len) };
    match ta_vwma(real, volume, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn wad(inputs: &[Series]) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (high_ptr, _high_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let high = unsafe { std::slice::from_raw_parts(high_ptr, len) };
    let (low_ptr, _low_owner) = get_series_f64_ptr(&mut prepared[1])?;
    let low = unsafe { std::slice::from_raw_parts(low_ptr, len) };
    let (close_ptr, _close_owner) = get_series_f64_ptr(&mut prepared[2])?;
    let close = unsafe { std::slice::from_raw_parts(close_ptr, len) };
    match ta_wad(high, low, close) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
#[polars_expr(output_type=Float64)]
fn zlema(inputs: &[Series], kwargs: ZlemaKwargs) -> PolarsResult<Series> {
    let len = inputs.iter().map(|s| s.len()).max().unwrap_or(0);
    let mut prepared = Vec::with_capacity(inputs.len());
    for s in inputs {
        let s = if s.len() == len {
            s.clone()
        } else if s.len() == 1 {
            s.new_from_index(0, len)
        } else {
            return Err(PolarsError::ShapeMismatch(
                "indicator input lengths differ".into(),
            ));
        };
        prepared.push(cast_series_to_f64(&s)?);
    }
    let (real_ptr, _real_owner) = get_series_f64_ptr(&mut prepared[0])?;
    let real = unsafe { std::slice::from_raw_parts(real_ptr, len) };
    match ta_zlema(real, &kwargs) {
        Ok(out) => Ok(Series::from_vec("", out)),
        Err(code) => ta_code2err(code),
    }
}
